### ISSUE TITLE
Нужно поставить и настроить точку появления игрока на уровне

### ISSUE THREAD

**Issue by DaKosss** [DaKosss/UE5_Horror#1]
При переходе из главного меню в саму игру, игрок появляется в не правильном месте.
![изображение](https://github.com/DaKosss/UE5_Horror/assets/112929982/4fee37ee-d498-4520-a099-7b09f5e238fe)

**Comment by SabyrbekulyNurdaulet** [comment]
сделал точку появления игрока 
![Снимок экрана 2023-10-11 201307](https://github.com/DaKosss/UE5_Horror/assets/124282813/210e4e52-a68d-4195-9f35-631319799019)
